# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
box: python:3.9-alpine
clab:
  binds:
  - clab_files/host3/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-vxlan-host3
interfaces:
- bridge: vxlan_13
  gateway:
    ipv4: 100.65.1.5/24
  ifindex: 1
  ifname: eth1
  ipv4: 100.65.1.9/24
  ipv6: 2001:db8:aa:1::9/64
  linkindex: 13
  mtu: 1500
  name: l2vpn-host3 -> [host1,leaf1,leaf3]
  neighbors:
  - ifname: eth2
    ipv4: 100.65.1.7/24
    ipv6: 2001:db8:aa:1::7/64
    node: host1
  - ifname: vlan1001
    ipv4: 100.65.1.3/24
    ipv6: 2001:db8:aa:1::3/64
    node: leaf1
  - ifname: vlan1001
    ipv4: 100.65.1.5/24
    ipv6: 2001:db8:aa:1::5/64
    node: leaf3
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.109
  mac: 08:4f:a9:00:00:09
module: {}
mtu: 1500
role: host
