# Ansible inventory created from ['/root/lacnic_ipv6dc/local_as/topology.yml', 'package:topology-defaults.yml']
#

hosts:
  router1:
    ipv6:
    - 2001:db8:1::1
  router2:
    ipv6:
    - 2001:db8:2::1
    - 2001:db8:ff::1
  router3:
    ipv6:
    - 2001:db8:3::1
    - 2001:db8:ff::2
netlab_name: local_as
netlab_provider: clab
paths_collect:
  dirs:
  - /root/lacnic_ipv6dc/local_as/fetch-config
  - /root/.netlab/fetch-config
  - /usr/local/lib/python3.8/dist-packages/netsim/ansible/tasks/fetch-config
paths_custom:
  dirs:
  - /root/lacnic_ipv6dc/local_as
  - /root/.netlab
  - /usr/local/lib/python3.8/dist-packages/netsim/extra
  files:
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''-'' + node_provider + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''/'' + inventory_hostname + ''.cfg'' }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''-'' + node_provider + ''.j2''
    }}'
  - '{{ custom_config + ''/'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + netlab_device_type +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.'' + ansible_network_os +
    ''.j2'' }}'
  - '{{ custom_config + ''.'' + inventory_hostname + ''.j2'' }}'
  - '{{ custom_config + ''.'' + netlab_device_type + ''.j2'' }}'
  - '{{ custom_config + ''.'' + ansible_network_os + ''.j2'' }}'
  - '{{ custom_config }}'
  - '{{ custom_config + ''.j2'' }}'
  tasks:
  - '{{ custom_config }}/deploy-{{ inventory_hostname }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ netlab_device_type }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}-{{ node_provider }}.yml'
  - '{{ custom_config }}/deploy.{{ ansible_network_os }}.yml'
  - '{{ custom_config }}/deploy.yml'
paths_deploy:
  dirs:
  - /root/lacnic_ipv6dc/local_as/tasks
  - /root/.netlab/tasks
  - /usr/local/lib/python3.8/dist-packages/netsim/ansible/tasks
  files:
  - '{{ netlab_device_type }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ netlab_device_type }}/{{ config_module }}.yml'
  - deploy-config/{{ netlab_device_type }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - '{{ ansible_network_os }}/{{ config_module }}-{{ provider|default(netlab_provider)
    }}.yml'
  - '{{ ansible_network_os }}/{{ config_module }}.yml'
  - deploy-config/{{ ansible_network_os }}-{{ provider|default(netlab_provider) }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
  tasks_generic:
  - deploy-config/{{ netlab_device_type }}-{{ node_provider }}.yml
  - deploy-config/{{ netlab_device_type }}.yml
  - deploy-config/{{ ansible_network_os }}-{{ node_provider }}.yml
  - deploy-config/{{ ansible_network_os }}.yml
paths_ready:
  dirs:
  - /root/lacnic_ipv6dc/local_as/readiness-check
  - /root/.netlab/readiness-check
  - /usr/local/lib/python3.8/dist-packages/netsim/ansible/tasks/readiness-check
  files:
  - '{{netlab_device_type}}-{{provider|default(netlab_provider)}}.yml'
  - '{{netlab_device_type}}.yml'
  - '{{ansible_network_os}}-{{provider|default(netlab_provider)}}.yml'
  - '{{ansible_network_os}}.yml'
paths_t_files:
  files:
  - '{{config_module}}/{{netlab_device_type}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{netlab_device_type}}.j2'
  - '{{config_module}}.{{netlab_device_type}}.j2'
  - '{{config_module}}/{{ansible_network_os}}-{{provider|default(netlab_provider)}}.j2'
  - '{{config_module}}/{{ansible_network_os}}.j2'
  - '{{config_module}}.{{ansible_network_os}}.j2'
  - '{{netlab_device_type}}/{{config_module}}.j2'
paths_templates:
  dirs:
  - /root/lacnic_ipv6dc/local_as/templates
  - /root/.netlab/templates
  - /usr/local/lib/python3.8/dist-packages/netsim/ansible/templates
  - /usr/local/lib/python3.8/dist-packages/netsim/daemons
paths_validate:
- /root/lacnic_ipv6dc/local_as/validate
pools:
  core:
    unnumbered: true
  l2only: {}
  lan:
    ipv6: 2001:db8:dd::/48
    prefix: 24
  loopback:
    ipv6: 2001:db8:100::/48
    prefix: 32
  mgmt:
    ipv4: 192.168.121.0/24
    mac: 08-4F-A9-00-00-00
    prefix: 24
    start: 100
  p2p:
    ipv6: 2001:db8:ff::/48
    prefix: 30
  router_id:
    ipv4: 10.0.0.0/24
    prefix: 32
  vrf_loopback:
    ipv4: 10.2.0.0/24
    prefix: 32
