# Ansible inventory created from ['/root/lacnic_ipv6dc/acceso_internet/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ibgp
    - ebgp
  advertise_loopback: true
  as: 64500
  community:
    ebgp:
    - standard
    - extended
    ibgp:
    - standard
    - extended
    ibgp_localas:
    - standard
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 64500
    ipv6: 2001:db8:64::2
    name: borde2
    type: ibgp
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  - activate:
      ipv6: true
    as: 65001
    ifindex: 4
    ipv6: 2001:db8:500:501::1
    name: transito1
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.101
box: ghcr.io/sysoleg/vyos-container
clab:
  binds:
  - /lib/modules:/lib/modules
  kind: linux
config:
- bordes.j2
hostname: clab-acceso_inter-borde1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 13
  mtu: 1500
  name: borde1 -> spine1
  neighbors:
  - ifname: eth5
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: true
  linkindex: 14
  mtu: 1500
  name: borde1 -> spine2
  neighbors:
  - ifname: eth5
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv6: 2001:db8:ff::/127
  linkindex: 17
  mtu: 1500
  name: borde1 -> borde2
  neighbors:
  - ifname: eth3
    ipv6: 2001:db8:ff::1/127
    node: borde2
  type: p2p
- ifindex: 4
  ifname: eth4
  ipv6: 2001:db8:500:501::/127
  linkindex: 18
  mtu: 1500
  name: borde1 -> transito1
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:500:501::1/127
    node: transito1
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: dum0
  ipv6: 2001:db8:64::1/128
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.201
  mac: 08:4f:a9:00:00:65
module:
- bgp
mtu: 1500
router_id: 10.0.0.101
