# Ansible inventory created from ['/root/lacnic_ipv6dc/bgp_para_clientes/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4220010001
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  - activate:
      ipv6: true
    as: 64501
    ifindex: 3
    ipv6: 2001:db8:aa:1::1
    name: host1
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.10
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf1/daemons:/etc/frr/daemons
  - clab_files/leaf1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- leaves_filtros.j2
hostname: clab-bgp_para_cli-leaf1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 1
  mtu: 1500
  name: leaf1 -> spine1
  neighbors:
  - ifname: eth1
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: true
  linkindex: 5
  mtu: 1500
  name: leaf1 -> spine2
  neighbors:
  - ifname: eth1
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv6: 2001:db8:aa:1::2/64
  linkindex: 9
  mtu: 1500
  name: leaf1 -> host1
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:aa:1::1/64
    node: host1
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:64:1::1/128
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.110
  mac: 08:4f:a9:00:00:0a
module:
- bgp
mtu: 1500
router_id: 10.0.0.10
