# Ansible inventory created from ['/root/lacnic_ipv6dc/local_as/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 64501
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 64500
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: router2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.1
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/router1/daemons:/etc/frr/daemons
  - clab_files/router1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-local_as-router1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 1
  mtu: 1500
  name: router1 -> router2
  neighbors:
  - bgp:
      local_as: 64500
    ifname: eth1
    ipv6: true
    node: router2
  pool: core
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:1::1/48
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
module:
- bgp
mtu: 1500
router_id: 10.0.0.1
