# Ansible inventory created from ['/root/lacnic_ipv6dc/acceso_internet_con_filtros/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 65002
  community:
    ebgp:
    - standard
    - extended
    ibgp:
    - standard
    - extended
    ibgp_localas:
    - standard
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 64500
    ifindex: 1
    ipv6: '2001:db8:500:502::'
    name: borde2
    type: ebgp
  - activate:
      ipv6: true
    as: 65001
    ifindex: 2
    ipv6: 2001:db8:ff::a
    name: transito1
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.8
box: ghcr.io/sysoleg/vyos-container
clab:
  binds:
  - /lib/modules:/lib/modules
  kind: linux
config:
- transitos.j2
hostname: clab-acceso_inter-transito2
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: 2001:db8:500:502::1/127
  linkindex: 19
  mtu: 1500
  name: transito2 -> borde2
  neighbors:
  - ifname: eth4
    ipv6: 2001:db8:500:502::/127
    node: borde2
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: 2001:db8:ff::b/127
  linkindex: 20
  mtu: 1500
  name: transito2 -> transito1
  neighbors:
  - ifname: eth2
    ipv6: 2001:db8:ff::a/127
    node: transito1
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: dum0
  ipv6: 2001:db8:502::502/48
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.108
  mac: 08:4f:a9:00:00:08
module:
- bgp
mtu: 1500
router_id: 10.0.0.8
