# Ansible inventory created from ['/root/lacnic_ipv6dc/dci/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
bgp:
  activate:
    ipv4:
    - ebgp
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4210010001
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - activate:
      ipv4: false
      ipv6: false
    as: 4210010001
    ipv4: 10.0.0.6
    ipv6: 2001:db8:1::22
    name: spine2a
    type: ibgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010001
    evpn: true
    ifindex: 1
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth1
    name: leaf1a
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010002
    evpn: true
    ifindex: 2
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth2
    name: leaf2a
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 64501
    ifindex: 3
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth3
    name: borde1a
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.5
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/spine1a/daemons:/etc/frr/daemons
  - clab_files/spine1a/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- spines_a.j2
evpn:
  session:
  - ebgp
  vlans: []
hostname: clab-dci-spine1a
interfaces:
- _parent_intf: lo
  _parent_ipv4: 10.0.0.5/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
  linkindex: 1
  mtu: 9000
  name: spine1a -> leaf1a
  neighbors:
  - ifname: eth1
    ipv4: true
    ipv6: true
    node: leaf1a
  pool: core
  role: external
  type: p2p
- _parent_intf: lo
  _parent_ipv4: 10.0.0.5/32
  ifindex: 2
  ifname: eth2
  ipv4: true
  ipv6: true
  linkindex: 2
  mtu: 9000
  name: spine1a -> leaf2a
  neighbors:
  - ifname: eth1
    ipv4: true
    ipv6: true
    node: leaf2a
  pool: core
  role: external
  type: p2p
- _parent_intf: lo
  _parent_ipv4: 10.0.0.5/32
  ifindex: 3
  ifname: eth3
  ipv4: true
  ipv6: true
  linkindex: 13
  mtu: 9000
  name: spine1a -> borde1a
  neighbors:
  - ifname: eth1
    ipv4: true
    ipv6: true
    node: borde1a
  pool: core
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.5/32
  ipv6: 2001:db8:1::11/128
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08:4f:a9:00:00:05
module:
- bgp
- evpn
mtu: 1500
