# Ansible inventory created from ['/root/lacnic_ipv6dc/servicio_bgp_simple/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 64504
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 4220010004
    ifindex: 1
    ipv6: 2001:db8:aa:4::2
    name: leaf4
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.4
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/host4/daemons:/etc/frr/daemons
  - clab_files/host4/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-servicio_bgp-host4
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: 2001:db8:aa:4::1/64
  linkindex: 12
  mtu: 1500
  name: host4 -> leaf4
  neighbors:
  - ifname: eth3
    ipv6: 2001:db8:aa:4::2/64
    node: leaf4
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:4::4/48
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
module:
- bgp
mtu: 1500
router_id: 10.0.0.4
