# Ansible inventory created from ['/root/lacnic_ipv6dc/labbasico/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
box: python:3.9-alpine
clab:
  binds:
  - clab_files/host2/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-labbasico-host2
interfaces:
- bridge: labbasico_10
  ifindex: 1
  ifname: eth1
  ipv6: 2001:db8:aa:2::2/64
  linkindex: 10
  mtu: 1500
  name: host2 -> leaf2
  neighbors:
  - ifname: eth3
    ipv6: 2001:db8:aa:2::b/64
    node: leaf2
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
module: {}
mtu: 1500
role: host
