# Ansible inventory created from ['/root/lacnic_ipv6dc/vecinos_dinamicos/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
box: python:3.9-alpine
clab:
  binds:
  - clab_files/host1/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-vecinos_dina-host1
interfaces:
- bridge: vecinos_di_9
  ifindex: 1
  ifname: eth1
  ipv6: 2001:db8:aa:1::1/64
  linkindex: 9
  mtu: 1500
  name: host1 -> leaf1
  neighbors:
  - ifname: eth3
    ipv6: 2001:db8:aa:1::a/64
    node: leaf1
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
module: {}
mtu: 1500
role: host
