# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan_l3/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
  vpnv6: true
bgp:
  activate:
    ipv4:
    - ebgp
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4220010002
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 1
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 2
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.2
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf2/daemons:/etc/frr/daemons
  - clab_files/leaf2/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
evpn:
  session:
  - ebgp
  vrfs:
  - azul
  - verde
hostname: clab-vxlan_l3-leaf2
interfaces:
- _parent_intf: lo
  _parent_ipv4: 10.0.0.2/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
  linkindex: 2
  mtu: 1500
  name: leaf2 -> spine1
  neighbors:
  - ifname: eth2
    ipv4: true
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- _parent_intf: lo
  _parent_ipv4: 10.0.0.2/32
  ifindex: 2
  ifname: eth2
  ipv4: true
  ipv6: true
  linkindex: 6
  mtu: 1500
  name: leaf2 -> spine2
  neighbors:
  - ifname: eth2
    ipv4: true
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: vxlan_l3_10
  ifindex: 3
  ifname: eth3
  ipv6: 2001:db8:21::2/64
  linkindex: 10
  mtu: 1500
  name: leaf2 -> host21
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:21::21/64
    node: host21
  role: stub
  type: lan
  vrf: azul
- bgp:
    advertise: true
  bridge: vxlan_l3_14
  ifindex: 4
  ifname: eth4
  ipv6: 2001:db8:22::2/64
  linkindex: 14
  mtu: 1500
  name: leaf2 -> host22
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:22::22/64
    node: host22
  role: stub
  type: lan
  vrf: verde
- bgp:
    advertise: true
  bridge: vxlan_l3_18
  ifindex: 5
  ifname: eth5
  ipv6: 2001:db8:bb:1::2/64
  linkindex: 18
  mtu: 1500
  name: leaf2 -> hostB
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:bb:1::b/64
    node: hostB
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.2/32
  ipv6: 2001:db8:64:2::2/128
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
module:
- vlan
- bgp
- vrf
- vxlan
- evpn
mtu: 1500
vrf:
  as: 65000
vrfs:
  azul:
    af:
      ipv6: true
    evpn:
      evi: 1
      rd: 10.0.0.2:1
      transit_vni: 200000
    export:
    - '65000:1'
    id: 1
    import:
    - '65000:1'
    rd: '65000:1'
    vrfidx: 100
  verde:
    af:
      ipv6: true
    evpn:
      evi: 2
      rd: 10.0.0.2:2
      transit_vni: 200001
    export:
    - '65000:2'
    id: 2
    import:
    - '65000:2'
    rd: '65000:2'
    vrfidx: 101
vxlan:
  domain: global
  flooding: evpn
  l3vnis:
  - azul
  - verde
  vtep: 10.0.0.2
  vtep_interface: lo
