# Ansible inventory created from ['/root/lacnic_ipv6dc/acceso_internet_con_filtros/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4220010003
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv6: true
    as: 4210010001
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.12
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf3/daemons:/etc/frr/daemons
  - clab_files/leaf3/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- leaves_filtros.j2
hostname: clab-acceso_inter-leaf3
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 3
  mtu: 1500
  name: leaf3 -> spine1
  neighbors:
  - ifname: eth3
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: true
  linkindex: 7
  mtu: 1500
  name: leaf3 -> spine2
  neighbors:
  - ifname: eth3
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: acceso_int_11
  ifindex: 3
  ifname: eth3
  ipv6: 2001:db8:aa:3::c/64
  linkindex: 11
  mtu: 1500
  name: leaf3 -> host3
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:aa:3::3/64
    node: host3
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:64:3::3/128
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.112
  mac: 08:4f:a9:00:00:0c
module:
- bgp
mtu: 1500
router_id: 10.0.0.12
