# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 64521
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 64510
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv6: true
    as: 64510
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  - activate: {}
    as: 64523
    evpn: true
    ifindex: 20000
    ipv4: 100.64.0.3
    ipv6: 2001:db8:64:3::3
    multihop: 255
    name: leaf3
    type: ebgp
  - activate:
      ipv4: false
      ipv6: true
    as: 64523
    evpn: true
    ifindex: 20001
    ipv4: 100.65.1.5
    ipv6: 2001:db8:aa:1::5
    name: leaf3
    type: ebgp
  next_hop_self: true
  router_id: 100.64.0.1
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf1/daemons:/etc/frr/daemons
  - clab_files/leaf1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- ebgp.multihop
evpn:
  session:
  - ebgp
  vlans:
  - azul
hostname: clab-vxlan-leaf1
interfaces:
- _parent_intf: lo0
  _parent_ipv4: 100.64.0.1/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
  linkindex: 1
  mtu: 1500
  name: leaf1 -> spine1
  neighbors:
  - ifname: eth1
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- _parent_intf: lo0
  _parent_ipv4: 100.64.0.1/32
  ifindex: 2
  ifname: eth2
  ipv4: true
  ipv6: true
  linkindex: 5
  mtu: 1500
  name: leaf1 -> spine2
  neighbors:
  - ifname: eth1
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: vxlan_9
  ifindex: 3
  ifname: eth3
  ipv4: 100.65.2.3/24
  ipv6: 2001:db8:aa:2::3/64
  linkindex: 9
  mtu: 1500
  name: leaf1 -> host1
  neighbors:
  - ifname: eth1
    ipv4: 100.65.2.7/24
    ipv6: 2001:db8:aa:2::7/64
    node: host1
  role: stub
  type: lan
- bridge: vxlan_11
  ifindex: 4
  ifname: eth4
  linkindex: 11
  mtu: 1500
  type: lan
  vlan:
    access: azul
    access_id: 1001
- bridge_group: 1
  ifindex: 20001
  ifname: vlan1001
  ipv4: 100.65.1.3/24
  ipv6: 2001:db8:aa:1::3/64
  name: VLAN azul (1001) -> [host1,host3,leaf3]
  neighbors:
  - ifname: eth2
    ipv4: 100.65.1.7/24
    ipv6: 2001:db8:aa:1::7/64
    node: host1
  - ifname: eth1
    ipv4: 100.65.1.9/24
    ipv6: 2001:db8:aa:1::9/64
    node: host3
  - ifname: vlan1001
    ipv4: 100.65.1.5/24
    ipv6: 2001:db8:aa:1::5/64
    node: leaf3
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
loopback:
  ifindex: 0
  ifname: lo0
  ipv4: 100.64.0.1/32
  ipv6: 2001:db8:64:1::1/64
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.103
  mac: 08:4f:a9:00:00:03
module:
- vlan
- bgp
- vxlan
- evpn
mtu: 1500
vlan:
  max_bridge_group: 1
vlans:
  azul:
    bridge_group: 1
    evpn:
      evi: 1001
      export:
      - 64496:1001
      import:
      - 64496:1001
      rd: 100.64.0.1:1001
    id: 1001
    mode: irb
    prefix:
      allocation: id_based
      ipv4: 100.65.1.0/24
      ipv6: 2001:db8:aa:1::/64
    vni: 101001
vxlan:
  domain: global
  flooding: evpn
  vlans:
  - azul
  vtep: 100.64.0.1
  vtep_interface: lo0
