# Ansible inventory created from ['/root/lacnic_ipv6dc/sin_numerar/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4210010001
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: false
    as: 4210010001
    ipv6: 2001:db8:64:22::22
    name: spine2
    type: ibgp
  - activate:
      ipv6: true
    as: 4220010001
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: leaf1
    type: ebgp
  - activate:
      ipv6: true
    as: 4220010002
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: leaf2
    type: ebgp
  - activate:
      ipv6: true
    as: 4220010003
    ifindex: 3
    ipv6: true
    local_if: eth3
    name: leaf3
    type: ebgp
  - activate:
      ipv6: true
    as: 4220010004
    ifindex: 4
    ipv6: true
    local_if: eth4
    name: leaf4
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.5
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/spine1/daemons:/etc/frr/daemons
  - clab_files/spine1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- spines.j2
hostname: clab-sin_numerar-spine1
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 1
  mtu: 1500
  name: spine1 -> leaf1
  neighbors:
  - ifname: eth1
    ipv6: true
    node: leaf1
  pool: core
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: true
  linkindex: 2
  mtu: 1500
  name: spine1 -> leaf2
  neighbors:
  - ifname: eth1
    ipv6: true
    node: leaf2
  pool: core
  role: external
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv6: true
  linkindex: 3
  mtu: 1500
  name: spine1 -> leaf3
  neighbors:
  - ifname: eth1
    ipv6: true
    node: leaf3
  pool: core
  role: external
  type: p2p
- ifindex: 4
  ifname: eth4
  ipv6: true
  linkindex: 4
  mtu: 1500
  name: spine1 -> leaf4
  neighbors:
  - ifname: eth1
    ipv6: true
    node: leaf4
  pool: core
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:64:11::11/128
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08:4f:a9:00:00:05
module:
- bgp
mtu: 1500
router_id: 10.0.0.5
