# Ansible inventory created from ['/root/lacnic_ipv6dc/unnumbered/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
bgp:
  activate:
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 64522
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv6: true
  neighbors:
  - activate:
      ipv6: true
    as: 64510
    ifindex: 1
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv6: true
    as: 64510
    ifindex: 2
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.4
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf2/daemons:/etc/frr/daemons
  - clab_files/leaf2/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
hostname: clab-unnumbered-leaf2
interfaces:
- ifindex: 1
  ifname: eth1
  ipv6: true
  linkindex: 2
  mtu: 1500
  name: leaf2 -> spine1
  neighbors:
  - ifname: eth2
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv6: true
  linkindex: 6
  mtu: 1500
  name: leaf2 -> spine2
  neighbors:
  - ifname: eth2
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
loopback:
  ifindex: 0
  ifname: lo0
  ipv6: 2001:db8:64:2::2/64
  neighbors: []
  type: loopback
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
module:
- bgp
mtu: 1500
router_id: 10.0.0.4
