# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan_l3/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv6: true
box: python:3.9-alpine
clab:
  binds:
  - clab_files/host11/hosts:/etc/hosts
  config_templates:
  - hosts:/etc/hosts
  kind: linux
hostname: clab-vxlan_l3-host11
interfaces:
- bridge: vxlan_l3_9
  ifindex: 1
  ifname: eth1
  ipv6: 2001:db8:11::11/48
  linkindex: 9
  mtu: 1500
  name: host11 -> leaf1
  neighbors:
  - ifname: eth3
    ipv6: 2001:db8:11::1/48
    node: leaf1
    vrf: AZUL
  role: stub
  type: lan
mgmt:
  ifname: eth0
  ipv4: 192.168.121.117
  mac: 08:4f:a9:00:00:11
mtu: 1500
role: host
