# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan_l2/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
bgp:
  activate:
    ipv4:
    - ebgp
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4220010002
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 1
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 2
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010001
    evpn: true
    ifindex: 6
    ipv4: 10.1.0.1
    ipv6: 2001:db8:1::1
    name: leaf1
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010003
    evpn: true
    ifindex: 6
    ipv4: 10.1.0.3
    ipv6: 2001:db8:1::3
    name: leaf3
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010004
    evpn: true
    ifindex: 6
    ipv4: 10.1.0.4
    ipv6: 2001:db8:1::4
    name: leaf4
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010001
    evpn: true
    ifindex: 7
    ipv4: 10.2.0.1
    ipv6: 2001:db8:2::1
    name: leaf1
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010003
    evpn: true
    ifindex: 7
    ipv4: 10.2.0.3
    ipv6: 2001:db8:2::3
    name: leaf3
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4220010004
    evpn: true
    ifindex: 7
    ipv4: 10.2.0.4
    ipv6: 2001:db8:2::4
    name: leaf4
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.2
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf2/daemons:/etc/frr/daemons
  - clab_files/leaf2/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
config:
- leaves.j2
evpn:
  session:
  - ebgp
  vlans:
  - azul
  - verde
hostname: clab-vxlan_l2-leaf2
interfaces:
- _parent_intf: lo
  _parent_ipv4: 10.0.0.2/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
  linkindex: 2
  mtu: 1500
  name: leaf2 -> spine1
  neighbors:
  - ifname: eth2
    ipv4: true
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- _parent_intf: lo
  _parent_ipv4: 10.0.0.2/32
  ifindex: 2
  ifname: eth2
  ipv4: true
  ipv6: true
  linkindex: 6
  mtu: 1500
  name: leaf2 -> spine2
  neighbors:
  - ifname: eth2
    ipv4: true
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- bridge: vxlan_l2_10
  ifindex: 3
  ifname: eth3
  linkindex: 10
  mtu: 1500
  type: lan
  vlan:
    access: azul
    access_id: 1000
- bridge: vxlan_l2_14
  ifindex: 4
  ifname: eth4
  linkindex: 14
  mtu: 1500
  type: lan
  vlan:
    access: verde
    access_id: 1001
- bgp:
    advertise: true
  bridge: vxlan_l2_18
  ifindex: 5
  ifname: eth5
  ipv6: 2001:db8:aa:1::2/64
  linkindex: 18
  mtu: 1500
  name: leaf2 -> hostB
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:aa:1::b/64
    node: hostB
  role: stub
  type: lan
- bridge_group: 1
  ifindex: 6
  ifname: vlan1000
  ipv4: 10.1.0.2/24
  ipv6: 2001:db8:1::2/48
  name: VLAN azul (1000) -> [host11,leaf1,host21,host31,leaf3,host41,leaf4]
  neighbors:
  - ifname: eth1
    ipv4: 10.1.0.17/24
    ipv6: 2001:db8:1::11/48
    node: host11
  - ifname: vlan1000
    ipv4: 10.1.0.1/24
    ipv6: 2001:db8:1::1/48
    node: leaf1
  - ifname: eth1
    ipv4: 10.1.0.33/24
    ipv6: 2001:db8:1::21/48
    node: host21
  - ifname: eth1
    ipv4: 10.1.0.49/24
    ipv6: 2001:db8:1::31/48
    node: host31
  - ifname: vlan1000
    ipv4: 10.1.0.3/24
    ipv6: 2001:db8:1::3/48
    node: leaf3
  - ifname: eth1
    ipv4: 10.1.0.65/24
    ipv6: 2001:db8:1::41/48
    node: host41
  - ifname: vlan1000
    ipv4: 10.1.0.4/24
    ipv6: 2001:db8:1::4/48
    node: leaf4
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
- bridge_group: 2
  ifindex: 7
  ifname: vlan1001
  ipv4: 10.2.0.2/24
  ipv6: 2001:db8:2::2/48
  name: VLAN verde (1001) -> [host12,leaf1,host22,host32,leaf3,host42,leaf4]
  neighbors:
  - ifname: eth1
    ipv4: 10.2.0.18/24
    ipv6: 2001:db8:2::12/48
    node: host12
  - ifname: vlan1001
    ipv4: 10.2.0.1/24
    ipv6: 2001:db8:2::1/48
    node: leaf1
  - ifname: eth1
    ipv4: 10.2.0.34/24
    ipv6: 2001:db8:2::22/48
    node: host22
  - ifname: eth1
    ipv4: 10.2.0.50/24
    ipv6: 2001:db8:2::32/48
    node: host32
  - ifname: vlan1001
    ipv4: 10.2.0.3/24
    ipv6: 2001:db8:2::3/48
    node: leaf3
  - ifname: eth1
    ipv4: 10.2.0.66/24
    ipv6: 2001:db8:2::42/48
    node: host42
  - ifname: vlan1001
    ipv4: 10.2.0.4/24
    ipv6: 2001:db8:2::4/48
    node: leaf4
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.2/32
  ipv6: 2001:db8:64:2::2/128
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.102
  mac: 08:4f:a9:00:00:02
module:
- vlan
- bgp
- vxlan
- evpn
mtu: 1500
vlan:
  max_bridge_group: 2
vlans:
  azul:
    bridge_group: 1
    evpn:
      evi: 1000
      export:
      - 65000:1000
      import:
      - 65000:1000
      rd: 10.0.0.2:1000
    id: 1000
    mode: irb
    prefix:
      allocation: id_based
      ipv4: 10.1.0.0/24
      ipv6: 2001:db8:1::/48
    vni: 101000
  verde:
    bridge_group: 2
    evpn:
      evi: 1001
      export:
      - 65000:1001
      import:
      - 65000:1001
      rd: 10.0.0.2:1001
    id: 1001
    mode: irb
    prefix:
      allocation: id_based
      ipv4: 10.2.0.0/24
      ipv6: 2001:db8:2::/48
    vni: 101001
vxlan:
  domain: global
  flooding: evpn
  vlans:
  - azul
  - verde
  vtep: 10.0.0.2
  vtep_interface: lo
