# Ansible inventory created from ['/root/lacnic_ipv6dc/vxlan_l3/topology.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
  ipv6: true
  vpnv6: true
bgp:
  activate:
    ipv4:
    - ebgp
    ipv6:
    - ebgp
  advertise_loopback: true
  as: 4220010001
  community:
    ebgp:
    - standard
    - large
    - extended
    ibgp:
    - standard
    - large
    - extended
    ibgp_localas:
    - standard
    - large
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 1
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth1
    name: spine1
    type: ebgp
  - activate:
      ipv4: true
      ipv6: true
    as: 4210010001
    evpn: true
    ifindex: 2
    ipv4: true
    ipv4_rfc8950: true
    ipv6: true
    local_if: eth2
    name: spine2
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.1
box: quay.io/frrouting/frr:9.1.0
clab:
  binds:
  - clab_files/leaf1/daemons:/etc/frr/daemons
  - clab_files/leaf1/hosts:/etc/hosts
  config_templates:
  - daemons:/etc/frr/daemons
  - hosts:/etc/hosts
  kind: linux
evpn:
  session:
  - ebgp
  vrfs:
  - azul
  - verde
hostname: clab-vxlan_l3-leaf1
interfaces:
- _parent_intf: lo
  _parent_ipv4: 10.0.0.1/32
  ifindex: 1
  ifname: eth1
  ipv4: true
  ipv6: true
  linkindex: 1
  mtu: 1500
  name: leaf1 -> spine1
  neighbors:
  - ifname: eth1
    ipv4: true
    ipv6: true
    node: spine1
  pool: core
  role: external
  type: p2p
- _parent_intf: lo
  _parent_ipv4: 10.0.0.1/32
  ifindex: 2
  ifname: eth2
  ipv4: true
  ipv6: true
  linkindex: 5
  mtu: 1500
  name: leaf1 -> spine2
  neighbors:
  - ifname: eth1
    ipv4: true
    ipv6: true
    node: spine2
  pool: core
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: vxlan_l3_9
  ifindex: 3
  ifname: eth3
  ipv6: 2001:db8:11::1/64
  linkindex: 9
  mtu: 1500
  name: leaf1 -> host11
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:11::11/64
    node: host11
  role: stub
  type: lan
  vrf: azul
- bgp:
    advertise: true
  bridge: vxlan_l3_13
  ifindex: 4
  ifname: eth4
  ipv6: 2001:db8:12::1/64
  linkindex: 13
  mtu: 1500
  name: leaf1 -> host12
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:12::12/64
    node: host12
  role: stub
  type: lan
  vrf: verde
- bgp:
    advertise: true
  bridge: vxlan_l3_17
  ifindex: 5
  ifname: eth5
  ipv6: 2001:db8:bb::1/64
  linkindex: 17
  mtu: 1500
  name: leaf1 -> hostA
  neighbors:
  - ifname: eth1
    ipv6: 2001:db8:bb::a/64
    node: hostA
  role: stub
  type: lan
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.1/32
  ipv6: 2001:db8:64:1::1/128
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
module:
- vlan
- bgp
- vrf
- vxlan
- evpn
mtu: 1500
vrf:
  as: 65000
vrfs:
  azul:
    af:
      ipv6: true
    evpn:
      evi: 1
      rd: 10.0.0.1:1
      transit_vni: 200000
    export:
    - '65000:1'
    id: 1
    import:
    - '65000:1'
    rd: '65000:1'
    vrfidx: 100
  verde:
    af:
      ipv6: true
    evpn:
      evi: 2
      rd: 10.0.0.1:2
      transit_vni: 200001
    export:
    - '65000:2'
    id: 2
    import:
    - '65000:2'
    rd: '65000:2'
    vrfidx: 101
vxlan:
  domain: global
  flooding: evpn
  l3vnis:
  - azul
  - verde
  vtep: 10.0.0.1
  vtep_interface: lo
