# Ansible inventory created from ['/root/lacnic_ipv6dc/unnumbered/topology.yml', 'package:topology-defaults.yml']
#

all: {}
as64510:
  hosts:
    spine1: {}
    spine2: {}
as64521:
  hosts:
    leaf1: {}
as64522:
  hosts:
    leaf2: {}
as64523:
  hosts:
    leaf3: {}
as64524:
  hosts:
    leaf4: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
frr:
  hosts:
    leaf1:
      ansible_host: clab-unnumbered-leaf1
      id: 3
    leaf2:
      ansible_host: clab-unnumbered-leaf2
      id: 4
    leaf3:
      ansible_host: clab-unnumbered-leaf3
      id: 5
    leaf4:
      ansible_host: clab-unnumbered-leaf4
      id: 6
    spine2:
      ansible_host: clab-unnumbered-spine2
      id: 2
modules:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    leaf4: {}
    spine1: {}
    spine2: {}
spine:
  hosts:
    spine1: {}
    spine2: {}
vyos:
  hosts:
    spine1:
      ansible_host: clab-unnumbered-spine1
      id: 1
