# Ansible inventory created from ['/root/lacnic_ipv6dc/acceso_internet/topology.yml', 'package:topology-defaults.yml']
#

all: {}
as4210010001:
  hosts:
    spine1: {}
    spine2: {}
as4220010001:
  hosts:
    leaf1: {}
as4220010002:
  hosts:
    leaf2: {}
as4220010003:
  hosts:
    leaf3: {}
as4220010004:
  hosts:
    leaf4: {}
as64500:
  hosts:
    borde1: {}
    borde2: {}
as65001:
  hosts:
    transito1: {}
as65002:
  hosts:
    transito2: {}
borde:
  hosts:
    borde1: {}
    borde2: {}
custom_configs:
  hosts:
    borde1: {}
    borde2: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    leaf4: {}
    spine1: {}
    spine2: {}
    transito1: {}
    transito2: {}
daemons:
  hosts: {}
frr:
  hosts:
    leaf1:
      ansible_host: clab-acceso_inter-leaf1
      id: 10
    leaf2:
      ansible_host: clab-acceso_inter-leaf2
      id: 11
    leaf3:
      ansible_host: clab-acceso_inter-leaf3
      id: 12
    leaf4:
      ansible_host: clab-acceso_inter-leaf4
      id: 13
    spine1:
      ansible_host: clab-acceso_inter-spine1
      id: 5
    spine2:
      ansible_host: clab-acceso_inter-spine2
      id: 6
hosts:
  hosts:
    host1: {}
    host2: {}
    host3: {}
    host4: {}
leaves:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    leaf4: {}
linux:
  hosts:
    host1:
      ansible_host: clab-acceso_inter-host1
      id: 1
    host2:
      ansible_host: clab-acceso_inter-host2
      id: 2
    host3:
      ansible_host: clab-acceso_inter-host3
      id: 3
    host4:
      ansible_host: clab-acceso_inter-host4
      id: 4
modules:
  hosts:
    borde1: {}
    borde2: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    leaf4: {}
    spine1: {}
    spine2: {}
    transito1: {}
    transito2: {}
spine:
  hosts:
    spine1: {}
    spine2: {}
transito:
  hosts:
    transito1: {}
    transito2: {}
vyos:
  hosts:
    borde1:
      ansible_host: clab-acceso_inter-borde1
      id: 101
    borde2:
      ansible_host: clab-acceso_inter-borde2
      id: 102
    transito1:
      ansible_host: clab-acceso_inter-transito1
      id: 7
    transito2:
      ansible_host: clab-acceso_inter-transito2
      id: 8
